name: EssentialsNK
version: "1.0.0"
api: ["1.0.0"]
author: Scallop
description: EssentialsNK
main: cn.yescallop.essentialsnk.EssentialsNK

permissions:
 essentialsnk.back:
  description: "Allows the user to use /back command"
  default: true
 essentialsnk.extinguish:
  description: "Allows the user to use /extinguish command"
  default: op
 essentialsnk.extinguish.other:
  description: "Allows the user to use /extinguish command on others"
  default: op