name: EssentialsNK
version: "1.0.0"
api: ["1.0.0"]
author: Scallop
description: EssentialsNK
main: cn.yescallop.essentialsnk.EssentialsNK

permissions:
 essentialsnk.back:
  default: true
 essentialsnk.break:
  default: op
 essentialsnk.broadcast:
  default: op
 essentialsnk.burn:
  default: op
 essentialsnk.burn.other:
  default: op
 essentialsnk.extinguish:
  default: op
 essentialsnk.extinguish.other:
  default: op