name: EssentialsNK
version: "1.0.0"
api: ["1.0.0"]
author: Scallop
description: EssentialsNK
main: cn.yescallop.essentialsnk.EssentialsNK

permissions:
 essentialsnk.back:
  default: true
 essentialsnk.break:
  default: op
 essentialsnk.broadcast:
  default: op
 essentialsnk.burn:
  default: op
 essentialsnk.clearinventory:
  default: op
 essentialsnk.clearinventory.other:
  default: op
 essentialsnk.compass:
  default: true
 essentialsnk.depth:
  default: true
 essentialsnk.extinguish:
  default: op
 essentialsnk.extinguish.other:
  default: op
 essentialsnk.fly:
  default: op
 essentialsnk.fly.other:
  default: op
 essentialsnk.getpos:
  default: true
 essentialsnk.getpos.other:
  default: op
 essentialsnk.heal:
  default: op
 essentialsnk.heal.other:
  default: op